package Scoops2Go.scoops2goapi.integration;

import Scoops2Go.scoops2goapi.dto.OrderDTO;
import Scoops2Go.scoops2goapi.dto.ProductDTO;
import Scoops2Go.scoops2goapi.dto.TreatDTO;
import Scoops2Go.scoops2goapi.exception.ResourceNotFoundException;
import Scoops2Go.scoops2goapi.service.OrderService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
@DisplayName("OrderService Integration Tests (Extra)")
class OrderServiceIntegrationTest {

    @Autowired
    private OrderService orderService;

    private ProductDTO createProductDTO(Long id, String name, BigDecimal price, String type) {
        return new ProductDTO(id, name, price, "description", List.of(), type);
    }

    @Test
    @DisplayName("INT_001: Create order with valid treat should persist to database")
    void testCreateOrder_PersistsToDatabase() {
        // Arrange
        ProductDTO cone = createProductDTO(1L, "Waffle Cone", BigDecimal.valueOf(2.00), "CONE");
        ProductDTO flavour = createProductDTO(4L, "Vanilla", BigDecimal.valueOf(1.00), "FLAVOR");
        TreatDTO treat = new TreatDTO(List.of(cone, flavour));
        OrderDTO incoming = new OrderDTO(0, LocalDateTime.now(), null, null, 0, null, List.of(treat));

        // Act
        OrderDTO result = orderService.createOrder(incoming);

        // Assert
        assertNotNull(result);
        assertTrue(result.orderId() > 0, "Order ID should be generated by database");
        assertNotNull(result.orderTime());
    }

    @Test
    @DisplayName("INT_002: Retrieve existing order from database")
    void testGetOrderById_FromDatabase() {
        // Arrange - first create an order
        ProductDTO cone = createProductDTO(1L, "Waffle Cone", BigDecimal.valueOf(2.00), "CONE");
        ProductDTO flavour = createProductDTO(4L, "Vanilla", BigDecimal.valueOf(1.00), "FLAVOR");
        TreatDTO treat = new TreatDTO(List.of(cone, flavour));
        OrderDTO incoming = new OrderDTO(0, LocalDateTime.now(), null, null, 0, null, List.of(treat));
        OrderDTO created = orderService.createOrder(incoming);

        // Act
        OrderDTO retrieved = orderService.getOrderById(created.orderId());

        // Assert
        assertNotNull(retrieved);
        assertEquals(created.orderId(), retrieved.orderId());
    }

    @Test
    @DisplayName("INT_003: Delete order removes from database")
    void testDeleteOrder_RemovesFromDatabase() {
        // Arrange
        ProductDTO cone = createProductDTO(1L, "Waffle Cone", BigDecimal.valueOf(2.00), "CONE");
        ProductDTO flavour = createProductDTO(4L, "Vanilla", BigDecimal.valueOf(1.00), "FLAVOR");
        TreatDTO treat = new TreatDTO(List.of(cone, flavour));
        OrderDTO incoming = new OrderDTO(0, LocalDateTime.now(), null, null, 0, null, List.of(treat));
        OrderDTO created = orderService.createOrder(incoming);

        // Act
        orderService.deleteOrder(created.orderId());

        // Assert
        assertThrows(ResourceNotFoundException.class,
                () -> orderService.getOrderById(created.orderId()));
    }
}
